/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppLoginIndexRouteImport } from './routes/_app/login/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppCrmEmpresasIndexRouteImport } from './routes/_app/crm/empresas/index'
import { Route as AppCrmDealsIndexRouteImport } from './routes/_app/crm/deals/index'
import { Route as AppCrmContatosIndexRouteImport } from './routes/_app/crm/contatos/index'
import { Route as AppAtendimentoCentralAjudaIndexRouteImport } from './routes/_app/atendimento/central-ajuda/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLoginIndexRoute = AppLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCrmEmpresasIndexRoute = AppCrmEmpresasIndexRouteImport.update({
  id: '/crm/empresas/',
  path: '/crm/empresas/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCrmDealsIndexRoute = AppCrmDealsIndexRouteImport.update({
  id: '/crm/deals/',
  path: '/crm/deals/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCrmContatosIndexRoute = AppCrmContatosIndexRouteImport.update({
  id: '/crm/contatos/',
  path: '/crm/contatos/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAtendimentoCentralAjudaIndexRoute =
  AppAtendimentoCentralAjudaIndexRouteImport.update({
    id: '/atendimento/central-ajuda/',
    path: '/atendimento/central-ajuda/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/login/': typeof AppLoginIndexRoute
  '/atendimento/central-ajuda/': typeof AppAtendimentoCentralAjudaIndexRoute
  '/crm/contatos/': typeof AppCrmContatosIndexRoute
  '/crm/deals/': typeof AppCrmDealsIndexRoute
  '/crm/empresas/': typeof AppCrmEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/login': typeof AppLoginIndexRoute
  '/atendimento/central-ajuda': typeof AppAtendimentoCentralAjudaIndexRoute
  '/crm/contatos': typeof AppCrmContatosIndexRoute
  '/crm/deals': typeof AppCrmDealsIndexRoute
  '/crm/empresas': typeof AppCrmEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/login/': typeof AppLoginIndexRoute
  '/_app/atendimento/central-ajuda/': typeof AppAtendimentoCentralAjudaIndexRoute
  '/_app/crm/contatos/': typeof AppCrmContatosIndexRoute
  '/_app/crm/deals/': typeof AppCrmDealsIndexRoute
  '/_app/crm/empresas/': typeof AppCrmEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar/'
    | '/login/'
    | '/atendimento/central-ajuda/'
    | '/crm/contatos/'
    | '/crm/deals/'
    | '/crm/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/atendimento/central-ajuda'
    | '/crm/contatos'
    | '/crm/deals'
    | '/crm/empresas'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/calendar/'
    | '/_app/login/'
    | '/_app/atendimento/central-ajuda/'
    | '/_app/crm/contatos/'
    | '/_app/crm/deals/'
    | '/_app/crm/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/login/': {
      id: '/_app/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/crm/empresas/': {
      id: '/_app/crm/empresas/'
      path: '/crm/empresas'
      fullPath: '/crm/empresas/'
      preLoaderRoute: typeof AppCrmEmpresasIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/crm/deals/': {
      id: '/_app/crm/deals/'
      path: '/crm/deals'
      fullPath: '/crm/deals/'
      preLoaderRoute: typeof AppCrmDealsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/crm/contatos/': {
      id: '/_app/crm/contatos/'
      path: '/crm/contatos'
      fullPath: '/crm/contatos/'
      preLoaderRoute: typeof AppCrmContatosIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/atendimento/central-ajuda/': {
      id: '/_app/atendimento/central-ajuda/'
      path: '/atendimento/central-ajuda'
      fullPath: '/atendimento/central-ajuda/'
      preLoaderRoute: typeof AppAtendimentoCentralAjudaIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppLoginIndexRoute: typeof AppLoginIndexRoute
  AppAtendimentoCentralAjudaIndexRoute: typeof AppAtendimentoCentralAjudaIndexRoute
  AppCrmContatosIndexRoute: typeof AppCrmContatosIndexRoute
  AppCrmDealsIndexRoute: typeof AppCrmDealsIndexRoute
  AppCrmEmpresasIndexRoute: typeof AppCrmEmpresasIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppLoginIndexRoute: AppLoginIndexRoute,
  AppAtendimentoCentralAjudaIndexRoute: AppAtendimentoCentralAjudaIndexRoute,
  AppCrmContatosIndexRoute: AppCrmContatosIndexRoute,
  AppCrmDealsIndexRoute: AppCrmDealsIndexRoute,
  AppCrmEmpresasIndexRoute: AppCrmEmpresasIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
