/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppCrmEmpresasIndexRouteImport } from './routes/_app/crm/empresas/index'
import { Route as AppCrmContatosIndexRouteImport } from './routes/_app/crm/contatos/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCrmEmpresasIndexRoute = AppCrmEmpresasIndexRouteImport.update({
  id: '/crm/empresas/',
  path: '/crm/empresas/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCrmContatosIndexRoute = AppCrmContatosIndexRouteImport.update({
  id: '/crm/contatos/',
  path: '/crm/contatos/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/crm/contatos/': typeof AppCrmContatosIndexRoute
  '/crm/empresas/': typeof AppCrmEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/crm/contatos': typeof AppCrmContatosIndexRoute
  '/crm/empresas': typeof AppCrmEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/crm/contatos/': typeof AppCrmContatosIndexRoute
  '/_app/crm/empresas/': typeof AppCrmEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/' | '/crm/contatos/' | '/crm/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/crm/contatos' | '/crm/empresas'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/calendar/'
    | '/_app/crm/contatos/'
    | '/_app/crm/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/crm/empresas/': {
      id: '/_app/crm/empresas/'
      path: '/crm/empresas'
      fullPath: '/crm/empresas/'
      preLoaderRoute: typeof AppCrmEmpresasIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/crm/contatos/': {
      id: '/_app/crm/contatos/'
      path: '/crm/contatos'
      fullPath: '/crm/contatos/'
      preLoaderRoute: typeof AppCrmContatosIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppCrmContatosIndexRoute: typeof AppCrmContatosIndexRoute
  AppCrmEmpresasIndexRoute: typeof AppCrmEmpresasIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppCrmContatosIndexRoute: AppCrmContatosIndexRoute,
  AppCrmEmpresasIndexRoute: AppCrmEmpresasIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
